#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
  . $HOME/.dmenurc
else
  DMENU='dmenu -i'
fi

GS=`cat ~/.archhist | $DMENU $*`

if grep -q "$GS" "$HOME/.archhist" ; then
    echo already exists in history
else
    echo $GS >> ~/.archhist
fi

firefox -new-tab "http://www.archlinux.org/packages/?sort=&q="$GS"&maintainer=&last_update=&flagged=&limit=50"